name: PyPI_Packaging

# Set a new package_version_number here for each new version of the packages you
# intend to publish.
variables:
- name: package_version_number
  value: 0.1.0

# Need a matrix of python versions for these builds

# Trigger this build whenever this pipeline file is changed. This way we will build
# new pypi packages each time we update the version number, or any other information
# listed here, like supported python versions.
trigger:
    branches:
        include:
        - dev
        - release
        - pypi-builds
    paths:
        include:
        - azure-pypi-pipeline.yml
        exclude:
        - /
 
jobs:

- job: Linux_Build_for_PyPI
  timeoutInMinutes: 90
  pool:
    vmImage: Ubuntu-18.04
  container:
    image: rstelzleni/usd-pypi-builder:latest
    options: -v /home/vsts/USDinst:/opt/USD/inst
  steps:
  - bash: |
      sudo mkdir /opt/USD
      sudo chmod u+w /opt/USD
      /opt/python/cp36-cp36m/bin/python build_scripts/build_usd.py --for-pypi --build-args USD,"-Xlinker --allow-shlib-undefined -DPXR_BUILD_USD_TOOLS=OFF -DPXR_INSTALL_LOCATION=../pxr/pluginfo" --no-imaging --no-examples --no-tutorials --build /opt/USD/gen/build --src /opt/USD/gen/src /opt/USD/inst -v
    displayName: 'Building USD'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: usd-pypi-linux
      targetPath: /home/vsts/USDinst

#- job: Windows_Build_for_PyPI
#  timeoutInMinutes: 90
#  pool:
#    vmImage: 'VS2017-Win2016'
#  steps:
#  - script: |
#      call C:\"Program Files (x86)"\"Microsoft Visual Studio"\2017\Enterprise\VC\Auxiliary\Build\vcvars64.bat
#      call set PYTHONLOCATION=C:\hostedtoolcache\windows\Python\2.7.18\x64
#      call set PYTHONBIN=%PYTHONLOCATION%\python.exe
#      call set PATH=%PYTHONLOCATION%;%PYTHONLOCATION%\Scripts;%PATH%
#      call set BOOST_ROOT=
#      call %PYTHONBIN% --version
#      call %PYTHONBIN% build_scripts/build_usd.py --for-pypi --build-args USD,"-DPXR_BUILD_USD_TOOLS=OFF -DPXR_INSTALL_LOCATION=../pxr/pluginfo" --no-imaging --no-examples --no-tutorials --build %HOME%/USDgen/build --src %HOME%/USDgen/src %HOME%/USDinst -v
#    displayName: 'Building USD'
#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'usd-pypi-win64'
#      targetPath: "D:/USDinst"
#
#- job: Mac_Build_for_PyPI
#  timeoutInMinutes: 90
#  pool:
#    vmImage: 'macOS-10.14'
#  steps:
#  - script: |
#      # The SYSTEM env var is used by the Makefile of glew and having it set trips it up
#      unset SYSTEM
#      /bin/bash -c "sudo xcode-select -s /Applications/Xcode_10.1.app/Contents/Developer"
#      python build_scripts/build_usd.py --for-pypi --build-args USD,"-DPXR_BUILD_USD_TOOLS=OFF -DPXR_INSTALL_LOCATION=../pxr/pluginfo" --no-imaging --no-examples --no-tutorials --generator Xcode --build $HOME/USDgen/build --src $HOME/USDgen/src $HOME/USDinst -v
#    displayName: 'Building USD'
#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'usd-pypi-macOS'
#      targetPath: "/Users/runner/USDinst"
#
